import type { Alert } from "@/components/AlertItem";

export const mockAlerts: Alert[] = [
  {
    id: "1",
    title: "Seismic Activity Detected — Magnitude 6.2",
    location: "Pacific Ring of Fire, Japan",
    severity: "high",
    timestamp: "2 minutes ago",
    category: "Geological",
    status: "active",
  },
  {
    id: "2",
    title: "Tropical Storm Approaching Coastal Region",
    location: "Gulf of Mexico, USA",
    severity: "critical",
    timestamp: "8 minutes ago",
    category: "Meteorological",
    status: "active",
  },
  {
    id: "3",
    title: "Wildfire Containment Below 30%",
    location: "Northern California, USA",
    severity: "critical",
    timestamp: "15 minutes ago",
    category: "Environmental",
    status: "monitoring",
  },
  {
    id: "4",
    title: "Air Quality Index Exceeds Hazardous Level",
    location: "New Delhi, India",
    severity: "high",
    timestamp: "32 minutes ago",
    category: "Environmental",
    status: "active",
  },
  {
    id: "5",
    title: "Flash Flood Warning Issued",
    location: "Rhine Valley, Germany",
    severity: "medium",
    timestamp: "1 hour ago",
    category: "Meteorological",
    status: "monitoring",
  },
  {
    id: "6",
    title: "Volcanic Ash Cloud Advisory",
    location: "Reykjavik, Iceland",
    severity: "medium",
    timestamp: "2 hours ago",
    category: "Geological",
    status: "monitoring",
  },
  {
    id: "7",
    title: "Minor Seismic Event Recorded",
    location: "Istanbul, Turkey",
    severity: "low",
    timestamp: "3 hours ago",
    category: "Geological",
    status: "resolved",
  },
  {
    id: "8",
    title: "Drought Conditions Escalating",
    location: "Sub-Saharan Africa",
    severity: "high",
    timestamp: "5 hours ago",
    category: "Environmental",
    status: "monitoring",
  },
];

export const mockRegions = [
  { name: "North America", incidents: 12, change: "+2", trend: "up" },
  { name: "Europe", incidents: 7, change: "-1", trend: "down" },
  { name: "Asia Pacific", incidents: 18, change: "+5", trend: "up" },
  { name: "Middle East", incidents: 9, change: "0", trend: "stable" },
  { name: "Africa", incidents: 14, change: "+3", trend: "up" },
  { name: "South America", incidents: 6, change: "-2", trend: "down" },
];
